version: '2'

services:

sut:
        build: .
                dockerfile: Dockerfile.test
        links:
                - web
web:
        build: .
                dockerfile: Dockerfile
        links:
                - redis
redis:
        image: redis
