services:
        sut:
                build: .
                dockerfile: Dockerfile.test
                links:
                        - web
        web:
                biild: .
                dockerfile: Dockerfile
                links:
                        - redis
        redis:
                image: redis
